name: Bug Report
description: Found a Bug that needs to be fixed?
body:
- type: checkboxes
  attributes:
    label: General Troubleshooting
    description: You confirm to have made the following checks first.
    options:
      - label: I have checked for similar issues on the Issue-tracker.
        required: true
      - label: I have checked for PRs that might already address this issue.
        required: true
- type: textarea
  attributes:
    label: "Expected Behaviour"
    description: "What did you expect the program to do?"
    placeholder: "Webserver should do ..."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Reproduction Steps"
    description: |-
      Please add the steps you use to reproduce this problem.  
      Put "N/A" if you don't have a reproducible setup.
  validations:
    required: true
- type: textarea
  attributes:
    label: "Exception or Error"
    description: |-
      Share any Exception or Error you encountered.  
      Leave this blank or put "N/A" if you don't have an Exception or Error.