name: Feature Request
description: Request a new feature
body:
- type: checkboxes
  attributes:
    label: General Troubleshooting
    description: You confirm to have made the following checks first.
    options:
      - label: I have checked for similar issues on the Issue-tracker.
        required: true
      - label: I have checked the branches or the maintainers' PRs for upcoming features.
        required: true
- type: textarea
  attributes:
    label: "Feature Request"
    description: "Provide a small description of the feature you want to have added."
    placeholder: "Werbserver should get ..."
  validations:
    required: true
- type: textarea
  attributes:
    label: "Example Use-Case"
    description: |-
      Provide some code or describe a possible use-case for this feature.